### ISSUE TITLE
[Removed - Opened in Error but Can't Figure out How to Delete] 

### ISSUE THREAD

**Issue by dAIsySHEng1** [cmu-cs-academy/desktop-cmu-graphics#80]
Sorry - totally wrong repo.

**Comment by Mohamed-Waiel-Shikfa** [comment]
![image](https://github.com/cmu-cs-academy/desktop-cmu-graphics/assets/140717221/8125f303-8cb0-49bc-8a7e-a910b78837e7)

I can see a close issue button on issues I opened. Maybe that's what you want...😅😉
