### ISSUE TITLE
Debug menu doesn't position properly with different app.width/height

### ISSUE THREAD

**Issue by HyperCodec** [cmu-cs-academy/desktop-cmu-graphics#85]
The debug menu (the current position and the info about the shape) that is supposed to render in the corner of the screen does not do so when the width and height are not the default values. It appears that the position of the menu is hardcoded instead of relative to the size of the screen.

**Comment by Yonokid** [comment]
I have opened a pull request here #86 which should fix this problem

**Comment by schmave** [comment]
Thank you for your bug report! We will work to get this fix merged soon.
