### ISSUE TITLE
Broken Appveyor with macOS 

### ISSUE THREAD

**Issue by Mohamed-Waiel-Shikfa** [cmu-cs-academy/desktop-cmu-graphics#91]
Hey, 
Since we are rapidly approaching term project season, I thought I would take a look at what are some changes I could make to improve the students experience.

I made changes to both the sound branch and the contributing guidelines branch and think they are now at a stage where they can be merged.

That being said the Appveyor build for mac failed. Examining the log revealed that it is doing updates which take so long that the build times out before testing anything. This wasn't happening previously, which leads me to think that something is wrong with the build environment.

If we could get this fixed and then merge some of the suggested improvement before TP1 (in 2 weeks) it would be awesome.

Best

**Comment by schmave** [comment]
Thanks for the report, Mohamed. I'm looking into this in PR #92
