### ISSUE TITLE
hosting desktop-cmu-graphics as the same functionality online

### ISSUE THREAD

**Issue by lucasw2025** [cmu-cs-academy/desktop-cmu-graphics#98]
is desktop-cmu-graphics hostable on a server to the same functionality as https://academy.cs.cmu.edu/?

**Comment by schmave** [comment]
No, there's no way to achieve that easily using desktop CMU graphics. The CS Academy website renders graphics using Brython, Javascript, and HTML Canvas, while desktop CMU Graphics uses CPython and Pygame. The logic is the same but the implementation is totally different.
